# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "artifact_parser.baml": "// BAML is used as a parser-only structural alignment layer. Runtime provider\n// calls continue to flow through ModelGateway, so third-party routing and\n// credentials stay under the application's existing authority boundary.\nclient ParserOnly {\n  provider openai-generic\n  options {\n    model \"parser-only\"\n    base_url \"http://127.0.0.1\"\n    api_key \"not-used\"\n  }\n}\n\nclass CausalCycleWire {\n  obstacle string\n  effort string\n  result string\n  state_change string\n}\n\nfunction ParseCausalCycles(raw_cycle_array: string) -> CausalCycleWire[] {\n  client ParserOnly\n  prompt #\"\n    Parse the supplied unique causal-cycle array. The object field names may\n    differ, but preserve each complete obstacle -> effort -> result ->\n    state-change cycle and its original order.\n\n    {{ raw_cycle_array }}\n  \"#\n}\n",
    "generators.baml": "generator novel_flywheel_python {\n  output_type \"python/pydantic\"\n  output_dir \"../src/novel_flywheel/baml_client\"\n  version \"0.223.0\"\n}\n",
}

def get_baml_files():
    return _file_map
